/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as VendorRouteImport } from './routes/_vendor'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppWebsiteRouteImport } from './routes/_app.website'
import { Route as AppVendorsRouteImport } from './routes/_app.vendors'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppGuestsRouteImport } from './routes/_app.guests'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCourtMarriageRouteImport } from './routes/_app.court-marriage'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppBudgetRouteImport } from './routes/_app.budget'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppPlannerIndexRouteImport } from './routes/_app.planner.index'
import { Route as ApiVendorDirectoryBackfillRouteImport } from './routes/api/vendor-directory/backfill'
import { Route as ApiBillingRazorpayRouteImport } from './routes/api/billing/razorpay'
import { Route as VendorVendorReviewsRouteImport } from './routes/_vendor.vendor.reviews'
import { Route as VendorVendorProfileRouteImport } from './routes/_vendor.vendor.profile'
import { Route as VendorVendorPackagesRouteImport } from './routes/_vendor.vendor.packages'
import { Route as VendorVendorLeadsRouteImport } from './routes/_vendor.vendor.leads'
import { Route as VendorVendorDashboardRouteImport } from './routes/_vendor.vendor.dashboard'
import { Route as VendorVendorCalendarRouteImport } from './routes/_vendor.vendor.calendar'
import { Route as AppWebsiteCustomRequestRouteImport } from './routes/_app.website.custom-request'
import { Route as AppPlannerThreadIdRouteImport } from './routes/_app.planner.$threadId'
import { Route as AdminAdminVendorsRouteImport } from './routes/_admin.admin.vendors'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminModerationRouteImport } from './routes/_admin.admin.moderation'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as AdminAdminCustomTemplateRequestsRouteImport } from './routes/_admin.admin.custom-template-requests'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/_vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebsiteRoute = AppWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppGuestsRoute = AppGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCourtMarriageRoute = AppCourtMarriageRouteImport.update({
  id: '/court-marriage',
  path: '/court-marriage',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerIndexRoute = AppPlannerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlannerRoute,
} as any)
const ApiVendorDirectoryBackfillRoute =
  ApiVendorDirectoryBackfillRouteImport.update({
    id: '/api/vendor-directory/backfill',
    path: '/api/vendor-directory/backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingRazorpayRoute = ApiBillingRazorpayRouteImport.update({
  id: '/api/billing/razorpay',
  path: '/api/billing/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorVendorReviewsRoute = VendorVendorReviewsRouteImport.update({
  id: '/vendor/reviews',
  path: '/vendor/reviews',
  getParentRoute: () => VendorRoute,
} as any)
const VendorVendorProfileRoute = VendorVendorProfileRouteImport.update({
  id: '/vendor/profile',
  path: '/vendor/profile',
  getParentRoute: () => VendorRoute,
} as any)
const VendorVendorPackagesRoute = VendorVendorPackagesRouteImport.update({
  id: '/vendor/packages',
  path: '/vendor/packages',
  getParentRoute: () => VendorRoute,
} as any)
const VendorVendorLeadsRoute = VendorVendorLeadsRouteImport.update({
  id: '/vendor/leads',
  path: '/vendor/leads',
  getParentRoute: () => VendorRoute,
} as any)
const VendorVendorDashboardRoute = VendorVendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => VendorRoute,
} as any)
const VendorVendorCalendarRoute = VendorVendorCalendarRouteImport.update({
  id: '/vendor/calendar',
  path: '/vendor/calendar',
  getParentRoute: () => VendorRoute,
} as any)
const AppWebsiteCustomRequestRoute = AppWebsiteCustomRequestRouteImport.update({
  id: '/custom-request',
  path: '/custom-request',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppPlannerThreadIdRoute = AppPlannerThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppPlannerRoute,
} as any)
const AdminAdminVendorsRoute = AdminAdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminModerationRoute = AdminAdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCustomTemplateRequestsRoute =
  AdminAdminCustomTemplateRequestsRouteImport.update({
    id: '/admin/custom-template-requests',
    path: '/admin/custom-template-requests',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/budget': typeof AppBudgetRoute
  '/calendar': typeof AppCalendarRoute
  '/court-marriage': typeof AppCourtMarriageRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/guests': typeof AppGuestsRoute
  '/messages': typeof AppMessagesRoute
  '/onboarding': typeof AppOnboardingRoute
  '/planner': typeof AppPlannerRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/timeline': typeof AppTimelineRoute
  '/vendors': typeof AppVendorsRoute
  '/website': typeof AppWebsiteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/w/$slug': typeof WSlugRoute
  '/admin/custom-template-requests': typeof AdminAdminCustomTemplateRequestsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/moderation': typeof AdminAdminModerationRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/vendors': typeof AdminAdminVendorsRoute
  '/planner/$threadId': typeof AppPlannerThreadIdRoute
  '/website/custom-request': typeof AppWebsiteCustomRequestRoute
  '/vendor/calendar': typeof VendorVendorCalendarRoute
  '/vendor/dashboard': typeof VendorVendorDashboardRoute
  '/vendor/leads': typeof VendorVendorLeadsRoute
  '/vendor/packages': typeof VendorVendorPackagesRoute
  '/vendor/profile': typeof VendorVendorProfileRoute
  '/vendor/reviews': typeof VendorVendorReviewsRoute
  '/api/billing/razorpay': typeof ApiBillingRazorpayRoute
  '/api/vendor-directory/backfill': typeof ApiVendorDirectoryBackfillRoute
  '/planner/': typeof AppPlannerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/budget': typeof AppBudgetRoute
  '/calendar': typeof AppCalendarRoute
  '/court-marriage': typeof AppCourtMarriageRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/guests': typeof AppGuestsRoute
  '/messages': typeof AppMessagesRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/timeline': typeof AppTimelineRoute
  '/vendors': typeof AppVendorsRoute
  '/website': typeof AppWebsiteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/w/$slug': typeof WSlugRoute
  '/admin/custom-template-requests': typeof AdminAdminCustomTemplateRequestsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/moderation': typeof AdminAdminModerationRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/vendors': typeof AdminAdminVendorsRoute
  '/planner/$threadId': typeof AppPlannerThreadIdRoute
  '/website/custom-request': typeof AppWebsiteCustomRequestRoute
  '/vendor/calendar': typeof VendorVendorCalendarRoute
  '/vendor/dashboard': typeof VendorVendorDashboardRoute
  '/vendor/leads': typeof VendorVendorLeadsRoute
  '/vendor/packages': typeof VendorVendorPackagesRoute
  '/vendor/profile': typeof VendorVendorProfileRoute
  '/vendor/reviews': typeof VendorVendorReviewsRoute
  '/api/billing/razorpay': typeof ApiBillingRazorpayRoute
  '/api/vendor-directory/backfill': typeof ApiVendorDirectoryBackfillRoute
  '/planner': typeof AppPlannerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_vendor': typeof VendorRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/budget': typeof AppBudgetRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/court-marriage': typeof AppCourtMarriageRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/guests': typeof AppGuestsRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/planner': typeof AppPlannerRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/_app/website': typeof AppWebsiteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/w/$slug': typeof WSlugRoute
  '/_admin/admin/custom-template-requests': typeof AdminAdminCustomTemplateRequestsRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/moderation': typeof AdminAdminModerationRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/vendors': typeof AdminAdminVendorsRoute
  '/_app/planner/$threadId': typeof AppPlannerThreadIdRoute
  '/_app/website/custom-request': typeof AppWebsiteCustomRequestRoute
  '/_vendor/vendor/calendar': typeof VendorVendorCalendarRoute
  '/_vendor/vendor/dashboard': typeof VendorVendorDashboardRoute
  '/_vendor/vendor/leads': typeof VendorVendorLeadsRoute
  '/_vendor/vendor/packages': typeof VendorVendorPackagesRoute
  '/_vendor/vendor/profile': typeof VendorVendorProfileRoute
  '/_vendor/vendor/reviews': typeof VendorVendorReviewsRoute
  '/api/billing/razorpay': typeof ApiBillingRazorpayRoute
  '/api/vendor-directory/backfill': typeof ApiVendorDirectoryBackfillRoute
  '/_app/planner/': typeof AppPlannerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/budget'
    | '/calendar'
    | '/court-marriage'
    | '/dashboard'
    | '/documents'
    | '/guests'
    | '/messages'
    | '/onboarding'
    | '/planner'
    | '/settings'
    | '/tasks'
    | '/timeline'
    | '/vendors'
    | '/website'
    | '/api/chat'
    | '/w/$slug'
    | '/admin/custom-template-requests'
    | '/admin/dashboard'
    | '/admin/moderation'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vendors'
    | '/planner/$threadId'
    | '/website/custom-request'
    | '/vendor/calendar'
    | '/vendor/dashboard'
    | '/vendor/leads'
    | '/vendor/packages'
    | '/vendor/profile'
    | '/vendor/reviews'
    | '/api/billing/razorpay'
    | '/api/vendor-directory/backfill'
    | '/planner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/budget'
    | '/calendar'
    | '/court-marriage'
    | '/dashboard'
    | '/documents'
    | '/guests'
    | '/messages'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/timeline'
    | '/vendors'
    | '/website'
    | '/api/chat'
    | '/w/$slug'
    | '/admin/custom-template-requests'
    | '/admin/dashboard'
    | '/admin/moderation'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vendors'
    | '/planner/$threadId'
    | '/website/custom-request'
    | '/vendor/calendar'
    | '/vendor/dashboard'
    | '/vendor/leads'
    | '/vendor/packages'
    | '/vendor/profile'
    | '/vendor/reviews'
    | '/api/billing/razorpay'
    | '/api/vendor-directory/backfill'
    | '/planner'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/_vendor'
    | '/auth'
    | '/_app/analytics'
    | '/_app/budget'
    | '/_app/calendar'
    | '/_app/court-marriage'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/guests'
    | '/_app/messages'
    | '/_app/onboarding'
    | '/_app/planner'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/timeline'
    | '/_app/vendors'
    | '/_app/website'
    | '/api/chat'
    | '/w/$slug'
    | '/_admin/admin/custom-template-requests'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/moderation'
    | '/_admin/admin/settings'
    | '/_admin/admin/users'
    | '/_admin/admin/vendors'
    | '/_app/planner/$threadId'
    | '/_app/website/custom-request'
    | '/_vendor/vendor/calendar'
    | '/_vendor/vendor/dashboard'
    | '/_vendor/vendor/leads'
    | '/_vendor/vendor/packages'
    | '/_vendor/vendor/profile'
    | '/_vendor/vendor/reviews'
    | '/api/billing/razorpay'
    | '/api/vendor-directory/backfill'
    | '/_app/planner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  VendorRoute: typeof VendorRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  WSlugRoute: typeof WSlugRoute
  ApiBillingRazorpayRoute: typeof ApiBillingRazorpayRoute
  ApiVendorDirectoryBackfillRoute: typeof ApiVendorDirectoryBackfillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_vendor': {
      id: '/_vendor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/website': {
      id: '/_app/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AppWebsiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guests': {
      id: '/_app/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AppGuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/court-marriage': {
      id: '/_app/court-marriage'
      path: '/court-marriage'
      fullPath: '/court-marriage'
      preLoaderRoute: typeof AppCourtMarriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner/': {
      id: '/_app/planner/'
      path: '/'
      fullPath: '/planner/'
      preLoaderRoute: typeof AppPlannerIndexRouteImport
      parentRoute: typeof AppPlannerRoute
    }
    '/api/vendor-directory/backfill': {
      id: '/api/vendor-directory/backfill'
      path: '/api/vendor-directory/backfill'
      fullPath: '/api/vendor-directory/backfill'
      preLoaderRoute: typeof ApiVendorDirectoryBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/razorpay': {
      id: '/api/billing/razorpay'
      path: '/api/billing/razorpay'
      fullPath: '/api/billing/razorpay'
      preLoaderRoute: typeof ApiBillingRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_vendor/vendor/reviews': {
      id: '/_vendor/vendor/reviews'
      path: '/vendor/reviews'
      fullPath: '/vendor/reviews'
      preLoaderRoute: typeof VendorVendorReviewsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_vendor/vendor/profile': {
      id: '/_vendor/vendor/profile'
      path: '/vendor/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorVendorProfileRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_vendor/vendor/packages': {
      id: '/_vendor/vendor/packages'
      path: '/vendor/packages'
      fullPath: '/vendor/packages'
      preLoaderRoute: typeof VendorVendorPackagesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_vendor/vendor/leads': {
      id: '/_vendor/vendor/leads'
      path: '/vendor/leads'
      fullPath: '/vendor/leads'
      preLoaderRoute: typeof VendorVendorLeadsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_vendor/vendor/dashboard': {
      id: '/_vendor/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorVendorDashboardRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_vendor/vendor/calendar': {
      id: '/_vendor/vendor/calendar'
      path: '/vendor/calendar'
      fullPath: '/vendor/calendar'
      preLoaderRoute: typeof VendorVendorCalendarRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_app/website/custom-request': {
      id: '/_app/website/custom-request'
      path: '/custom-request'
      fullPath: '/website/custom-request'
      preLoaderRoute: typeof AppWebsiteCustomRequestRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/planner/$threadId': {
      id: '/_app/planner/$threadId'
      path: '/$threadId'
      fullPath: '/planner/$threadId'
      preLoaderRoute: typeof AppPlannerThreadIdRouteImport
      parentRoute: typeof AppPlannerRoute
    }
    '/_admin/admin/vendors': {
      id: '/_admin/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminAdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/moderation': {
      id: '/_admin/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminAdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/custom-template-requests': {
      id: '/_admin/admin/custom-template-requests'
      path: '/admin/custom-template-requests'
      fullPath: '/admin/custom-template-requests'
      preLoaderRoute: typeof AdminAdminCustomTemplateRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminCustomTemplateRequestsRoute: typeof AdminAdminCustomTemplateRequestsRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminModerationRoute: typeof AdminAdminModerationRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminVendorsRoute: typeof AdminAdminVendorsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCustomTemplateRequestsRoute: AdminAdminCustomTemplateRequestsRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminModerationRoute: AdminAdminModerationRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminVendorsRoute: AdminAdminVendorsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppPlannerRouteChildren {
  AppPlannerThreadIdRoute: typeof AppPlannerThreadIdRoute
  AppPlannerIndexRoute: typeof AppPlannerIndexRoute
}

const AppPlannerRouteChildren: AppPlannerRouteChildren = {
  AppPlannerThreadIdRoute: AppPlannerThreadIdRoute,
  AppPlannerIndexRoute: AppPlannerIndexRoute,
}

const AppPlannerRouteWithChildren = AppPlannerRoute._addFileChildren(
  AppPlannerRouteChildren,
)

interface AppWebsiteRouteChildren {
  AppWebsiteCustomRequestRoute: typeof AppWebsiteCustomRequestRoute
}

const AppWebsiteRouteChildren: AppWebsiteRouteChildren = {
  AppWebsiteCustomRequestRoute: AppWebsiteCustomRequestRoute,
}

const AppWebsiteRouteWithChildren = AppWebsiteRoute._addFileChildren(
  AppWebsiteRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBudgetRoute: typeof AppBudgetRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCourtMarriageRoute: typeof AppCourtMarriageRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppGuestsRoute: typeof AppGuestsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPlannerRoute: typeof AppPlannerRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppWebsiteRoute: typeof AppWebsiteRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBudgetRoute: AppBudgetRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCourtMarriageRoute: AppCourtMarriageRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppGuestsRoute: AppGuestsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPlannerRoute: AppPlannerRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppWebsiteRoute: AppWebsiteRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface VendorRouteChildren {
  VendorVendorCalendarRoute: typeof VendorVendorCalendarRoute
  VendorVendorDashboardRoute: typeof VendorVendorDashboardRoute
  VendorVendorLeadsRoute: typeof VendorVendorLeadsRoute
  VendorVendorPackagesRoute: typeof VendorVendorPackagesRoute
  VendorVendorProfileRoute: typeof VendorVendorProfileRoute
  VendorVendorReviewsRoute: typeof VendorVendorReviewsRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorVendorCalendarRoute: VendorVendorCalendarRoute,
  VendorVendorDashboardRoute: VendorVendorDashboardRoute,
  VendorVendorLeadsRoute: VendorVendorLeadsRoute,
  VendorVendorPackagesRoute: VendorVendorPackagesRoute,
  VendorVendorProfileRoute: VendorVendorProfileRoute,
  VendorVendorReviewsRoute: VendorVendorReviewsRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  VendorRoute: VendorRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  WSlugRoute: WSlugRoute,
  ApiBillingRazorpayRoute: ApiBillingRazorpayRoute,
  ApiVendorDirectoryBackfillRoute: ApiVendorDirectoryBackfillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
