export type Ceremony = {
  name: string;
  optional?: boolean;
};

export type CeremonyRegion = {
  id: string;
  label: string;
  ceremonies: Ceremony[];
};

export type CeremonyTradition = {
  id: string;
  label: string;
  description: string;
  ceremonies: Ceremony[];
  regions?: CeremonyRegion[];
};

function ceremonies(names: string[], optional: string[] = []): Ceremony[] {
  return names.map((name) => ({ name, optional: optional.includes(name) }));
}

export const ceremonyTraditions: CeremonyTradition[] = [
  {
    id: "hindu",
    label: "Hindu",
    description: "A flexible base plan with regional and family customs.",
    ceremonies: ceremonies(
      [
        "Roka",
        "Sagai / Engagement",
        "Chunni Ceremony",
        "Tilak",
        "Ganesh Puja",
        "Grah Shanti Puja",
        "Mandap Muhurat",
        "Haldi",
        "Mehendi",
        "Sangeet",
        "Mata Ki Chowki / Jagran",
        "Kalash Sthapana",
        "Baraat",
        "Milni",
        "Dwar Puja",
        "Jaimala / Varmala",
        "Kanyadaan",
        "Hast Milap",
        "Gathbandhan",
        "Agni Puja",
        "Mangal Pheras (Saat Phere)",
        "Saptapadi",
        "Sindoor Daan",
        "Mangalsutra Ceremony",
        "Ashirwad",
        "Vidaai",
        "Griha Pravesh",
        "Reception",
        "Pag Phera",
        "Satyanarayan Puja",
      ],
      ["Mata Ki Chowki / Jagran", "Satyanarayan Puja"],
    ),
    regions: [
      {
        id: "north-india",
        label: "North India",
        ceremonies: ceremonies([
          "Roka",
          "Tilak",
          "Mehendi",
          "Haldi",
          "Sangeet",
          "Baraat",
          "Jaimala",
          "Saat Phere",
          "Vidaai",
          "Reception",
        ]),
      },
      {
        id: "south-india",
        label: "South India",
        ceremonies: ceremonies([
          "Nischayathartham",
          "Vratham",
          "Janavasam",
          "Kasi Yatra",
          "Oonjal",
          "Kanyadaanam",
          "Mangalya Dharanam",
          "Saptapadi",
          "Nalangu",
          "Reception",
        ]),
      },
      {
        id: "bengali",
        label: "Bengali",
        ceremonies: ceremonies([
          "Aiburo Bhaat",
          "Gaye Holud",
          "Dodhi Mongol",
          "Bor Jatri",
          "Shubho Drishti",
          "Mala Badal",
          "Sampradan",
          "Saat Paak",
          "Sindoor Daan",
          "Bashor Ghar",
          "Bou Bhaat",
        ]),
      },
      {
        id: "marathi",
        label: "Marathi",
        ceremonies: ceremonies([
          "Sakhar Puda",
          "Kelvan",
          "Halad Chadavane",
          "Simant Pujan",
          "Antarpat",
          "Mangalashtaka",
          "Saptapadi",
          "Lajahoma",
          "Griha Pravesh",
        ]),
      },
      {
        id: "gujarati",
        label: "Gujarati",
        ceremonies: ceremonies([
          "Chandlo Matli",
          "Gol Dhana",
          "Mandap Muhurat",
          "Grah Shanti",
          "Mehendi",
          "Garba",
          "Pithi",
          "Jaan",
          "Jaimala",
          "Hasta Milap",
          "Mangal Phera",
          "Saptapadi",
          "Vidaai",
        ]),
      },
      {
        id: "tamil",
        label: "Tamil",
        ceremonies: ceremonies([
          "Nichayathartham",
          "Panda Kaal Muhurtham",
          "Vratham",
          "Kasi Yatra",
          "Oonjal",
          "Kanyadanam",
          "Mangalya Dharanam",
          "Sapthapadi",
          "Nalangu",
        ]),
      },
      {
        id: "telugu",
        label: "Telugu",
        ceremonies: ceremonies([
          "Pellikuthuru",
          "Snathakam",
          "Kasi Yatra",
          "Jeelakarra Bellam",
          "Mangalasutra Dharana",
          "Talambralu",
          "Saptapadi",
          "Appagintalu",
        ]),
      },
      {
        id: "kannada",
        label: "Kannada",
        ceremonies: ceremonies([
          "Nischaya Tamulam",
          "Devara Puja",
          "Haldi",
          "Kasi Yatra",
          "Dhare Herdu",
          "Mangalya Dharane",
          "Saptapadi",
          "Reception",
        ]),
      },
      {
        id: "punjabi",
        label: "Punjabi",
        ceremonies: ceremonies([
          "Roka",
          "Chunni",
          "Kurmai",
          "Maiyan",
          "Mehendi",
          "Jaggo",
          "Choora",
          "Kalire",
          "Ghodi",
          "Milni",
          "Anand Karaj / Hindu Wedding",
          "Vidaai",
        ]),
      },
    ],
  },
  {
    id: "muslim",
    label: "Muslim (Nikah)",
    description: "Nikah events with room for family customs and local names.",
    ceremonies: ceremonies([
      "Mangni (Engagement)",
      "Imam Zamin",
      "Manjha / Haldi",
      "Mehendi",
      "Sanchaq",
      "Sehra Bandi",
      "Baraat",
      "Nikah",
      "Khutbah",
      "Mehr",
      "Ijab-o-Qubool",
      "Nikahnama Signing",
      "Dua",
      "Rukhsati",
      "Doodh Pilai",
      "Muh Dikhai",
      "Walima",
    ]),
  },
  {
    id: "christian",
    label: "Christian",
    description: "Church ceremony, celebration, and reception moments.",
    ceremonies: ceremonies(
      [
        "Engagement",
        "Bridal Shower",
        "Bachelor Party",
        "Bachelorette Party",
        "Rehearsal Dinner",
        "Wedding Mass / Church Ceremony",
        "Processional",
        "Exchange of Vows",
        "Exchange of Rings",
        "Blessing",
        "Holy Communion",
        "Signing Marriage Register",
        "Pronouncement",
        "Reception",
        "First Dance",
        "Cake Cutting",
        "Bouquet Toss",
        "Send-off",
      ],
      ["Holy Communion"],
    ),
  },
  {
    id: "sikh",
    label: "Sikh (Anand Karaj)",
    description: "An Anand Karaj plan with pre-wedding and family ceremonies.",
    ceremonies: ceremonies([
      "Roka",
      "Kurmai (Engagement)",
      "Maiyan",
      "Mehendi",
      "Jaggo",
      "Sangeet",
      "Choora Ceremony",
      "Kalire Ceremony",
      "Ghara Gharoli",
      "Sehra Bandi",
      "Milni",
      "Anand Karaj",
      "Ardas",
      "Palla Rasam",
      "Laavan (4 Pheras)",
      "Anand Sahib",
      "Hukamnama",
      "Langar",
      "Vidaai",
      "Reception",
    ]),
  },
  {
    id: "buddhist",
    label: "Buddhist",
    description: "A blessing-centred ceremony plan.",
    ceremonies: ceremonies([
      "Engagement",
      "Family Blessing",
      "Monk Blessing",
      "Offering to Monks",
      "Chanting",
      "Garland Exchange",
      "Ring Exchange",
      "Vows",
      "Water Pouring Ceremony",
      "Parents' Blessing",
      "Reception",
    ]),
  },
  {
    id: "jewish",
    label: "Jewish",
    description: "A Jewish wedding flow, including optional preparation rituals.",
    ceremonies: ceremonies(
      [
        "Aufruf",
        "Mikveh",
        "Kabbalat Panim",
        "Bedeken",
        "Chuppah Ceremony",
        "Kiddushin",
        "Ring Exchange",
        "Ketubah Signing",
        "Sheva Brachot",
        "Breaking the Glass",
        "Yichud",
        "Reception",
      ],
      ["Mikveh"],
    ),
  },
  {
    id: "parsi",
    label: "Parsi (Zoroastrian)",
    description: "A traditional Parsi wedding ceremony sequence.",
    ceremonies: ceremonies([
      "Rupia Peravanu",
      "Madhavsaro",
      "Adarni",
      "Nahan",
      "Achu Michu",
      "Ara Antar",
      "Haath Borvanu",
      "Rice Throwing",
      "Ashirvad Ceremony",
      "Reception",
    ]),
  },
  {
    id: "jain",
    label: "Jain",
    description: "A Jain wedding plan with core family and mandap rituals.",
    ceremonies: ceremonies([
      "Lagan Patrika",
      "Sagai",
      "Grah Shanti",
      "Mehendi",
      "Haldi",
      "Mandap Muhurat",
      "Baraat",
      "Jaimala",
      "Kanyadaan",
      "Pheras",
      "Saptapadi",
      "Sindoor",
      "Vidaai",
      "Reception",
    ]),
  },
  {
    id: "mixed",
    label: "Mixed or family-led",
    description: "Build a personal ceremony list from scratch or mix traditions.",
    ceremonies: [],
  },
];
