export const weddingTemplateIds = [
  "editorial",
  "botanical",
  "midnight",
  "terracotta",
  "coastal",
  "regency",
  "modern-minimal",
  "celestial",
  "marigold",
  "vintage",
  "monogram",
  "lavender",
  "tropical",
  "pearl",
  "art-deco",
  "autumn",
  "rosewater",
  "desert",
  "emerald",
  "citrus",
  "atlas",
  "blush",
  "heritage",
  "starlight",
] as const;

export type WeddingTemplateId = (typeof weddingTemplateIds)[number];

type TemplateLayout = "classic" | "modern" | "romantic" | "split";

export type WeddingTemplate = {
  id: WeddingTemplateId;
  name: string;
  description: string;
  collection: string;
  layout: TemplateLayout;
  mode: "light" | "dark";
  preview: string;
  surface: string;
  text: string;
  muted: string;
  border: string;
  card: string;
  accent: string;
  button: string;
  chip: string;
  heroFallback: string;
  heroOverlay: string;
  heading: string;
};

export const weddingTemplates: WeddingTemplate[] = [
  {
    id: "editorial",
    name: "Timeless editorial",
    description: "Soft neutrals and refined serif type.",
    collection: "Classic",
    layout: "classic",
    mode: "light",
    preview: "from-[#fff8f5] via-[#f6e7e5] to-[#ead0cf] text-[#4b302e]",
    surface: "bg-[#fffaf7]",
    text: "text-[#513432]",
    muted: "text-[#513432]/65",
    border: "border-[#ead7d3]",
    card: "border-[#ead7d3] bg-white/70",
    accent: "text-[#be5963]",
    button: "bg-[#be5963] text-white hover:bg-[#a94b55]",
    chip: "border-[#513432]/10 bg-white/60 text-[#513432]/70",
    heroFallback: "from-[#efd9d2] to-[#cda4a1]",
    heroOverlay: "from-[#fffaf7] via-[#fffaf7]/25 to-transparent",
    heading: "font-display",
  },
  {
    id: "botanical",
    name: "Garden party",
    description: "Fresh blooms for an airy, joyful day.",
    collection: "Garden",
    layout: "romantic",
    mode: "light",
    preview: "from-[#fbf5e8] via-[#ebf1df] to-[#cdddbd] text-[#2e4c38]",
    surface: "bg-[#f4f8ec]",
    text: "text-[#294839]",
    muted: "text-[#294839]/65",
    border: "border-[#d9e6c7]",
    card: "border-[#d9e6c7] bg-white/60",
    accent: "text-[#54814c]",
    button: "bg-[#54814c] text-white hover:bg-[#416d3b]",
    chip: "border-[#294839]/10 bg-white/60 text-[#294839]/70",
    heroFallback: "from-[#e0efd4] to-[#bdcfb7]",
    heroOverlay: "from-[#f4f8ec] via-[#f4f8ec]/25 to-transparent",
    heading: "font-display",
  },
  {
    id: "midnight",
    name: "After dark",
    description: "Dramatic ink and a golden finish.",
    collection: "Evening",
    layout: "classic",
    mode: "dark",
    preview: "from-[#1e1d2a] via-[#3a3047] to-[#6a4e42] text-[#fffaf0]",
    surface: "bg-[#252131]",
    text: "text-[#fffaf0]",
    muted: "text-white/68",
    border: "border-white/10",
    card: "border-white/12 bg-white/6",
    accent: "text-[#e5bf75]",
    button: "bg-[#e5bf75] text-[#332923] hover:bg-[#f0cb81]",
    chip: "border-white/15 bg-white/10 text-white/75",
    heroFallback: "from-[#2f2840] to-[#17151f]",
    heroOverlay: "from-[#252131] via-[#252131]/35 to-[#252131]/10",
    heading: "font-display",
  },
  {
    id: "terracotta",
    name: "Terracotta vows",
    description: "Sun-warmed clay, citrus, and celebration.",
    collection: "Destination",
    layout: "split",
    mode: "light",
    preview: "from-[#fff1df] via-[#e7b58a] to-[#be6a4a] text-[#5a2c20]",
    surface: "bg-[#fff6ea]",
    text: "text-[#5a2c20]",
    muted: "text-[#5a2c20]/65",
    border: "border-[#ecc9ad]",
    card: "border-[#ecc9ad] bg-white/65",
    accent: "text-[#bd5a3e]",
    button: "bg-[#bd5a3e] text-white hover:bg-[#a74931]",
    chip: "border-[#5a2c20]/10 bg-white/65 text-[#5a2c20]/70",
    heroFallback: "from-[#f1c08e] to-[#c76a49]",
    heroOverlay: "from-[#fff6ea] via-[#fff6ea]/20 to-transparent",
    heading: "font-display",
  },
  {
    id: "coastal",
    name: "Coastal blue",
    description: "A clean seaside gathering in blue and sand.",
    collection: "Destination",
    layout: "modern",
    mode: "light",
    preview: "from-[#f1fafb] via-[#b8dce0] to-[#5f9eae] text-[#16485a]",
    surface: "bg-[#f5fbfb]",
    text: "text-[#16485a]",
    muted: "text-[#16485a]/65",
    border: "border-[#bfdee2]",
    card: "border-[#bfdee2] bg-white/70",
    accent: "text-[#27768a]",
    button: "bg-[#27768a] text-white hover:bg-[#1d6476]",
    chip: "border-[#16485a]/10 bg-white/70 text-[#16485a]/70",
    heroFallback: "from-[#bfe3e7] to-[#5f9eae]",
    heroOverlay: "from-[#f5fbfb] via-[#f5fbfb]/20 to-transparent",
    heading: "font-sans font-semibold tracking-tight",
  },
  {
    id: "regency",
    name: "Regency romance",
    description: "Candlelit blush with old-world details.",
    collection: "Romantic",
    layout: "romantic",
    mode: "light",
    preview: "from-[#fff6f0] via-[#efd5d1] to-[#b8898d] text-[#5c3037]",
    surface: "bg-[#fff8f3]",
    text: "text-[#5c3037]",
    muted: "text-[#5c3037]/65",
    border: "border-[#ead0cb]",
    card: "border-[#ead0cb] bg-white/70",
    accent: "text-[#a45161]",
    button: "bg-[#a45161] text-white hover:bg-[#8e4050]",
    chip: "border-[#5c3037]/10 bg-white/70 text-[#5c3037]/70",
    heroFallback: "from-[#f3d9d2] to-[#bb858b]",
    heroOverlay: "from-[#fff8f3] via-[#fff8f3]/25 to-transparent",
    heading: "font-display italic",
  },
  {
    id: "modern-minimal",
    name: "Modern minimal",
    description: "Crisp type and a pared-back gallery feel.",
    collection: "Modern",
    layout: "modern",
    mode: "light",
    preview: "from-[#ffffff] via-[#ecebe7] to-[#b7b6ad] text-[#20201e]",
    surface: "bg-[#fafaf8]",
    text: "text-[#20201e]",
    muted: "text-[#20201e]/60",
    border: "border-[#deddd7]",
    card: "border-[#deddd7] bg-white",
    accent: "text-[#20201e]",
    button: "bg-[#20201e] text-white hover:bg-[#393936]",
    chip: "border-[#20201e]/10 bg-white text-[#20201e]/65",
    heroFallback: "from-[#e5e4df] to-[#a9a79f]",
    heroOverlay: "from-[#fafaf8] via-[#fafaf8]/20 to-transparent",
    heading: "font-sans font-semibold tracking-tight",
  },
  {
    id: "celestial",
    name: "Celestial night",
    description: "Indigo skies with luminous champagne accents.",
    collection: "Evening",
    layout: "romantic",
    mode: "dark",
    preview: "from-[#121932] via-[#303a6f] to-[#8b7ab8] text-[#fffdf5]",
    surface: "bg-[#151a35]",
    text: "text-[#fffdf5]",
    muted: "text-[#e4e6ff]/68",
    border: "border-[#bec7ff]/15",
    card: "border-[#bec7ff]/15 bg-white/6",
    accent: "text-[#f1d595]",
    button: "bg-[#f1d595] text-[#25203a] hover:bg-[#fae3ae]",
    chip: "border-white/15 bg-white/10 text-white/75",
    heroFallback: "from-[#3b4787] to-[#12172e]",
    heroOverlay: "from-[#151a35] via-[#151a35]/35 to-[#151a35]/10",
    heading: "font-display",
  },
  {
    id: "marigold",
    name: "Marigold mehfil",
    description: "Joyful marigold and fuchsia for a big celebration.",
    collection: "Celebration",
    layout: "split",
    mode: "light",
    preview: "from-[#fff8db] via-[#f9bf3c] to-[#d84d5d] text-[#74262b]",
    surface: "bg-[#fff9e9]",
    text: "text-[#74262b]",
    muted: "text-[#74262b]/65",
    border: "border-[#f4cb73]",
    card: "border-[#f4cb73] bg-white/65",
    accent: "text-[#d34554]",
    button: "bg-[#d34554] text-white hover:bg-[#bd3546]",
    chip: "border-[#74262b]/10 bg-white/65 text-[#74262b]/70",
    heroFallback: "from-[#f8c84c] to-[#d85758]",
    heroOverlay: "from-[#fff9e9] via-[#fff9e9]/20 to-transparent",
    heading: "font-display",
  },
  {
    id: "vintage",
    name: "Vintage garden",
    description: "Faded paper, olive leaves, and heirloom charm.",
    collection: "Classic",
    layout: "classic",
    mode: "light",
    preview: "from-[#f8f0db] via-[#c9c29e] to-[#7d8a62] text-[#3e4930]",
    surface: "bg-[#f9f5e8]",
    text: "text-[#3e4930]",
    muted: "text-[#3e4930]/65",
    border: "border-[#d8d1b5]",
    card: "border-[#d8d1b5] bg-[#fffdf6]/75",
    accent: "text-[#6b7c4c]",
    button: "bg-[#6b7c4c] text-white hover:bg-[#59693d]",
    chip: "border-[#3e4930]/10 bg-white/65 text-[#3e4930]/70",
    heroFallback: "from-[#d9d0a8] to-[#87916b]",
    heroOverlay: "from-[#f9f5e8] via-[#f9f5e8]/25 to-transparent",
    heading: "font-display",
  },
  {
    id: "monogram",
    name: "Monogram",
    description: "A tailored black-tie stationery-inspired suite.",
    collection: "Classic",
    layout: "modern",
    mode: "light",
    preview: "from-[#f9f7f2] via-[#dbd0bc] to-[#8b765e] text-[#342a20]",
    surface: "bg-[#fbfaf7]",
    text: "text-[#342a20]",
    muted: "text-[#342a20]/62",
    border: "border-[#ded5c7]",
    card: "border-[#ded5c7] bg-white/80",
    accent: "text-[#7d654b]",
    button: "bg-[#342a20] text-white hover:bg-[#514437]",
    chip: "border-[#342a20]/10 bg-white text-[#342a20]/65",
    heroFallback: "from-[#ddd1bc] to-[#8f775b]",
    heroOverlay: "from-[#fbfaf7] via-[#fbfaf7]/20 to-transparent",
    heading: "font-display",
  },
  {
    id: "lavender",
    name: "Lavender haze",
    description: "Dreamy lilac gradients with a modern touch.",
    collection: "Romantic",
    layout: "modern",
    mode: "light",
    preview: "from-[#faf7ff] via-[#d9c8f4] to-[#967abe] text-[#493766]",
    surface: "bg-[#faf8ff]",
    text: "text-[#493766]",
    muted: "text-[#493766]/65",
    border: "border-[#dfd2f2]",
    card: "border-[#dfd2f2] bg-white/70",
    accent: "text-[#7653a7]",
    button: "bg-[#7653a7] text-white hover:bg-[#62458e]",
    chip: "border-[#493766]/10 bg-white/70 text-[#493766]/70",
    heroFallback: "from-[#ddcdf5] to-[#9678bd]",
    heroOverlay: "from-[#faf8ff] via-[#faf8ff]/20 to-transparent",
    heading: "font-display",
  },
  {
    id: "tropical",
    name: "Tropical bloom",
    description: "Lush foliage and bright coral optimism.",
    collection: "Garden",
    layout: "split",
    mode: "light",
    preview: "from-[#e8f4dc] via-[#77ae75] to-[#e67563] text-[#174c40]",
    surface: "bg-[#f4faed]",
    text: "text-[#174c40]",
    muted: "text-[#174c40]/65",
    border: "border-[#c3dfb2]",
    card: "border-[#c3dfb2] bg-white/65",
    accent: "text-[#d76255]",
    button: "bg-[#d76255] text-white hover:bg-[#bd5046]",
    chip: "border-[#174c40]/10 bg-white/65 text-[#174c40]/70",
    heroFallback: "from-[#71ae75] to-[#e87963]",
    heroOverlay: "from-[#f4faed] via-[#f4faed]/20 to-transparent",
    heading: "font-display",
  },
  {
    id: "pearl",
    name: "Pearl & champagne",
    description: "Quiet luxury in pearl, cream, and gold.",
    collection: "Romantic",
    layout: "romantic",
    mode: "light",
    preview: "from-[#fffef9] via-[#eee7d9] to-[#c9ad7b] text-[#62523d]",
    surface: "bg-[#fffdf8]",
    text: "text-[#62523d]",
    muted: "text-[#62523d]/63",
    border: "border-[#e8deca]",
    card: "border-[#e8deca] bg-white/75",
    accent: "text-[#ac8651]",
    button: "bg-[#ac8651] text-white hover:bg-[#946f3f]",
    chip: "border-[#62523d]/10 bg-white/70 text-[#62523d]/70",
    heroFallback: "from-[#f2eadd] to-[#c6aa75]",
    heroOverlay: "from-[#fffdf8] via-[#fffdf8]/25 to-transparent",
    heading: "font-display italic",
  },
  {
    id: "art-deco",
    name: "Art deco",
    description: "Geometric glamour in black, ivory, and brass.",
    collection: "Evening",
    layout: "modern",
    mode: "dark",
    preview: "from-[#141414] via-[#31302c] to-[#b69a5a] text-[#fff9ea]",
    surface: "bg-[#181817]",
    text: "text-[#fff9ea]",
    muted: "text-[#fff9ea]/67",
    border: "border-[#d5b969]/20",
    card: "border-[#d5b969]/20 bg-white/5",
    accent: "text-[#d9bd70]",
    button: "bg-[#d9bd70] text-[#211e17] hover:bg-[#ecd38c]",
    chip: "border-[#d9bd70]/25 bg-white/8 text-[#fff9ea]/80",
    heroFallback: "from-[#38362f] to-[#161614]",
    heroOverlay: "from-[#181817] via-[#181817]/35 to-[#181817]/10",
    heading: "font-sans font-semibold tracking-[0.04em]",
  },
  {
    id: "autumn",
    name: "Autumn harvest",
    description: "Rich berry, copper, and late-afternoon warmth.",
    collection: "Seasonal",
    layout: "classic",
    mode: "light",
    preview: "from-[#fff2e5] via-[#d48752] to-[#7d3041] text-[#592936]",
    surface: "bg-[#fff7ee]",
    text: "text-[#592936]",
    muted: "text-[#592936]/65",
    border: "border-[#e6bd9c]",
    card: "border-[#e6bd9c] bg-white/68",
    accent: "text-[#9c4050]",
    button: "bg-[#9c4050] text-white hover:bg-[#843443]",
    chip: "border-[#592936]/10 bg-white/65 text-[#592936]/70",
    heroFallback: "from-[#de9863] to-[#86364b]",
    heroOverlay: "from-[#fff7ee] via-[#fff7ee]/25 to-transparent",
    heading: "font-display",
  },
  {
    id: "rosewater",
    name: "Rosewater",
    description: "A light, floral canvas for an intimate wedding.",
    collection: "Romantic",
    layout: "romantic",
    mode: "light",
    preview: "from-[#fff8fa] via-[#f1ccd6] to-[#d4879b] text-[#6d3b50]",
    surface: "bg-[#fff9fb]",
    text: "text-[#6d3b50]",
    muted: "text-[#6d3b50]/65",
    border: "border-[#f0d3db]",
    card: "border-[#f0d3db] bg-white/72",
    accent: "text-[#c5617d]",
    button: "bg-[#c5617d] text-white hover:bg-[#ad4d69]",
    chip: "border-[#6d3b50]/10 bg-white/70 text-[#6d3b50]/70",
    heroFallback: "from-[#f0ccd6] to-[#d68ba0]",
    heroOverlay: "from-[#fff9fb] via-[#fff9fb]/25 to-transparent",
    heading: "font-display italic",
  },
  {
    id: "desert",
    name: "Desert modern",
    description: "Dune tones and strong contemporary typography.",
    collection: "Destination",
    layout: "modern",
    mode: "light",
    preview: "from-[#fff7ed] via-[#d8b38c] to-[#a76547] text-[#4c3327]",
    surface: "bg-[#fff9f1]",
    text: "text-[#4c3327]",
    muted: "text-[#4c3327]/64",
    border: "border-[#ead1b6]",
    card: "border-[#ead1b6] bg-white/72",
    accent: "text-[#a85d3f]",
    button: "bg-[#a85d3f] text-white hover:bg-[#914a30]",
    chip: "border-[#4c3327]/10 bg-white/70 text-[#4c3327]/70",
    heroFallback: "from-[#e2bd92] to-[#aa6647]",
    heroOverlay: "from-[#fff9f1] via-[#fff9f1]/20 to-transparent",
    heading: "font-sans font-semibold tracking-tight",
  },
  {
    id: "emerald",
    name: "Emerald evening",
    description: "Deep green, candlelight, and classic romance.",
    collection: "Evening",
    layout: "split",
    mode: "dark",
    preview: "from-[#0d2924] via-[#1f594b] to-[#b59255] text-[#fff9e9]",
    surface: "bg-[#112a25]",
    text: "text-[#fff9e9]",
    muted: "text-[#e7f0dc]/68",
    border: "border-[#c8ad6b]/18",
    card: "border-[#c8ad6b]/18 bg-white/6",
    accent: "text-[#e1c277]",
    button: "bg-[#e1c277] text-[#273026] hover:bg-[#f0d48e]",
    chip: "border-white/15 bg-white/10 text-white/75",
    heroFallback: "from-[#23604f] to-[#10241f]",
    heroOverlay: "from-[#112a25] via-[#112a25]/35 to-[#112a25]/10",
    heading: "font-display",
  },
  {
    id: "citrus",
    name: "Citrus grove",
    description: "Playful lemon, olive, and sunlit details.",
    collection: "Garden",
    layout: "split",
    mode: "light",
    preview: "from-[#fffce9] via-[#d9df71] to-[#7aa05a] text-[#3d5a32]",
    surface: "bg-[#fffdeb]",
    text: "text-[#3d5a32]",
    muted: "text-[#3d5a32]/65",
    border: "border-[#d9df9a]",
    card: "border-[#d9df9a] bg-white/68",
    accent: "text-[#718d3f]",
    button: "bg-[#718d3f] text-white hover:bg-[#5d7730]",
    chip: "border-[#3d5a32]/10 bg-white/70 text-[#3d5a32]/70",
    heroFallback: "from-[#dbe175] to-[#7ea45c]",
    heroOverlay: "from-[#fffdeb] via-[#fffdeb]/20 to-transparent",
    heading: "font-display",
  },
  {
    id: "atlas",
    name: "Atlas",
    description: "Cool stone and strong geometry for city vows.",
    collection: "Modern",
    layout: "modern",
    mode: "light",
    preview: "from-[#f5f7f8] via-[#b8c4cc] to-[#637789] text-[#253644]",
    surface: "bg-[#f7fafb]",
    text: "text-[#253644]",
    muted: "text-[#253644]/62",
    border: "border-[#d0dce2]",
    card: "border-[#d0dce2] bg-white/75",
    accent: "text-[#46687e]",
    button: "bg-[#46687e] text-white hover:bg-[#37596d]",
    chip: "border-[#253644]/10 bg-white text-[#253644]/65",
    heroFallback: "from-[#c0ced5] to-[#687c8c]",
    heroOverlay: "from-[#f7fafb] via-[#f7fafb]/20 to-transparent",
    heading: "font-sans font-semibold tracking-tight",
  },
  {
    id: "blush",
    name: "Blush bloom",
    description: "Soft pink petals with a fresh, friendly mood.",
    collection: "Romantic",
    layout: "romantic",
    mode: "light",
    preview: "from-[#fff8f8] via-[#f2d2d1] to-[#d9908e] text-[#713f42]",
    surface: "bg-[#fffafa]",
    text: "text-[#713f42]",
    muted: "text-[#713f42]/64",
    border: "border-[#f0d5d3]",
    card: "border-[#f0d5d3] bg-white/72",
    accent: "text-[#ca6e70]",
    button: "bg-[#ca6e70] text-white hover:bg-[#b7595d]",
    chip: "border-[#713f42]/10 bg-white/70 text-[#713f42]/70",
    heroFallback: "from-[#f0d2d0] to-[#d99391]",
    heroOverlay: "from-[#fffafa] via-[#fffafa]/25 to-transparent",
    heading: "font-display",
  },
  {
    id: "heritage",
    name: "Heritage",
    description: "Deep wine, cream paper, and formal ceremony.",
    collection: "Classic",
    layout: "classic",
    mode: "light",
    preview: "from-[#fff8ee] via-[#dac8ad] to-[#733a44] text-[#542a32]",
    surface: "bg-[#fffaf1]",
    text: "text-[#542a32]",
    muted: "text-[#542a32]/64",
    border: "border-[#e5d3ba]",
    card: "border-[#e5d3ba] bg-white/75",
    accent: "text-[#813f4d]",
    button: "bg-[#813f4d] text-white hover:bg-[#6d303d]",
    chip: "border-[#542a32]/10 bg-white/70 text-[#542a32]/70",
    heroFallback: "from-[#dfccb0] to-[#783e48]",
    heroOverlay: "from-[#fffaf1] via-[#fffaf1]/25 to-transparent",
    heading: "font-display",
  },
  {
    id: "starlight",
    name: "Starlight",
    description: "A sparkling plum night made for dancing.",
    collection: "Evening",
    layout: "romantic",
    mode: "dark",
    preview: "from-[#24192f] via-[#623d72] to-[#d3a967] text-[#fffafa]",
    surface: "bg-[#251a30]",
    text: "text-[#fffafa]",
    muted: "text-[#f3e5f4]/68",
    border: "border-[#d3a967]/20",
    card: "border-[#d3a967]/20 bg-white/6",
    accent: "text-[#edc879]",
    button: "bg-[#edc879] text-[#33233a] hover:bg-[#f7d991]",
    chip: "border-white/15 bg-white/10 text-white/75",
    heroFallback: "from-[#633e74] to-[#21182b]",
    heroOverlay: "from-[#251a30] via-[#251a30]/35 to-[#251a30]/10",
    heading: "font-display italic",
  },
];

export function isWeddingTemplateId(value: string): value is WeddingTemplateId {
  return weddingTemplateIds.includes(value as WeddingTemplateId);
}

export function getWeddingTemplate(value: string | null | undefined): WeddingTemplate {
  return weddingTemplates.find((template) => template.id === value) ?? weddingTemplates[0];
}
